
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo2
{
public partial class Tbicon
{
    private readonly System.Collections.Generic.Dictionary<int, demo2.icon> _dataMap;
    private readonly System.Collections.Generic.List<demo2.icon> _dataList;
    
    public Tbicon(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, demo2.icon>(count);
        _dataList = new System.Collections.Generic.List<demo2.icon>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            demo2.icon _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.demo2.icon.Deserializeicon(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, demo2.icon> DataMap => _dataMap;
    public System.Collections.Generic.List<demo2.icon> DataList => _dataList;

    public demo2.icon GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo2.icon Get(int key) => _dataMap[key];
    public demo2.icon this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

