
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.demo
{
public sealed partial class Language : Luban.BeanBase
{
    public Language(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["text_zh​"].IsString) { throw new SerializationException(); }  TextZh​ = _buf["text_zh​"]; }
        { if(!_buf["text_en​"].IsString) { throw new SerializationException(); }  TextEn​ = _buf["text_en​"]; }
        { if(!_buf["text_ja​"].IsString) { throw new SerializationException(); }  TextJa​ = _buf["text_ja​"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static Language DeserializeLanguage(JSONNode _buf)
    {
        return new demo.Language(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 中文
    /// </summary>
    public readonly string TextZh​;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string TextEn​;
    /// <summary>
    /// 日文
    /// </summary>
    public readonly string TextJa​;
    /// <summary>
    /// 注释
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = -847914205;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "textZh​:" + TextZh​ + ","
        + "textEn​:" + TextEn​ + ","
        + "textJa​:" + TextJa​ + ","
        + "desc:" + Desc + ","
        + "}";
    }
}
}

