
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public demo.Tbitem Tbitem {get; }
    public demo.TbLanguage TbLanguage {get; }
    public demo2.Tbicon Tbicon {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        Tbitem = new demo.Tbitem(loader("demo_tbitem"));
        TbLanguage = new demo.TbLanguage(loader("demo_tblanguage"));
        Tbicon = new demo2.Tbicon(loader("demo2_tbicon"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Tbitem.ResolveRef(this);
        TbLanguage.ResolveRef(this);
        Tbicon.ResolveRef(this);
    }
}

}
