
        using System.Collections.Generic;
        using UnityEngine;

        public class RequireComponentDatas
        {
            // 存储字符串数据的字段
            public static readonly List<string> stringList = new List<string>(){ 
"UnityEngine.AI.NavMeshAgent,UnityEngine.AIModule",
"UnityEngine.ParticleSystemRenderer,UnityEngine.ParticleSystemModule",
"MoreMountains.Tools.MMFollowTarget,MoreMountains.Tools",
"UnityEngine.Collider,UnityEngine.PhysicsModule",
"SWS.splineMove,Assembly-CSharp",
"InputBuffer,Assembly-CSharp",
"UnityEngine.InputSystem.PlayerInput,Unity.InputSystem",
"UnityEngine.Camera,UnityEngine.CoreModule",
"UnityEngine.CanvasRenderer,UnityEngine.UIModule",
"UnityEngine.RectTransform,UnityEngine.CoreModule",
"NodeCanvas.StateMachines.FSMOwner,NodeCanvas",
"FMODUnity.StudioListener,FMODUnity",
"UnityEngine.Animator,UnityEngine.AnimationModule",
"EscapeGame.InteractiveObjects.IAODetonateBehav,Assembly-CSharp",
"GameCreator.Runtime.Stats.Traits,GameCreator.Runtime.Stats",
"UnityEngine.Rigidbody,UnityEngine.PhysicsModule",
"UnityEngine.Rendering.Volume,Unity.RenderPipelines.Core.Runtime",
"UnityEngine.MeshCollider,UnityEngine.PhysicsModule",
"UnityEngine.PolygonCollider2D,UnityEngine.Physics2DModule",
"UnityEngine.MeshFilter,UnityEngine.CoreModule",
"UnityEngine.MeshRenderer,UnityEngine.CoreModule",
"Micosmo.SensorToolkit.FOVCollider,Micosmo.SensorToolkit",
"Micosmo.SensorToolkit.FOVCollider2D,Micosmo.SensorToolkit",
"UnityEngine.AudioListener,UnityEngine.AudioModule",
"UnityEngine.Collider2D,UnityEngine.Physics2DModule",
"UnityEngine.CanvasGroup,UnityEngine.UIModule",
"UnityEngine.UI.Image,UnityEngine.UI",
"UnityEngine.UI.Slider,UnityEngine.UI",
"UnityEngine.ParticleSystem,UnityEngine.ParticleSystemModule",
"UnityEngine.UI.Text,UnityEngine.UI",
"UnityEngine.LineRenderer,UnityEngine.CoreModule",
"UnityEngine.SpriteRenderer,UnityEngine.CoreModule",
"UnityEngine.Tilemaps.Tilemap,UnityEngine.TilemapModule",
"UnityEngine.Rendering.Tests.RemoveComponent+Apple,Unity.RenderPipelines.Core.Editor.Tests",
"UnityEngine.Rendering.Tests.RemoveComponent+Banana,Unity.RenderPipelines.Core.Editor.Tests",
"Lightbug.CharacterControllerPro.Core.CharacterBody,com.lightbug.character-controller-pro",
"UnityEngine.Light,UnityEngine.CoreModule",
"UnityEngine.EdgeCollider2D,UnityEngine.Physics2DModule",
"UnityEngine.Animations.Rigging.RigBuilder,Unity.Animation.Rigging",
"Cinemachine.CinemachineVirtualCamera,Cinemachine",
"Cinemachine.CinemachineFreeLook,Cinemachine",
"Cinemachine.CinemachineBrain,Cinemachine",
"UnityEngine.Renderer,UnityEngine.CoreModule",
"UnityEngine.VFX.VisualEffect,UnityEngine.VFXModule",
"UnityEngine.VFX.Utility.VFXPropertyBinder,Unity.VisualEffectGraph.Runtime",
"UnityEngine.AudioDistortionFilter,UnityEngine.AudioModule",
"UnityEngine.AudioEchoFilter,UnityEngine.AudioModule",
"UnityEngine.AudioHighPassFilter,UnityEngine.AudioModule",
"UnityEngine.AudioLowPassFilter,UnityEngine.AudioModule",
"UnityEngine.AudioReverbFilter,UnityEngine.AudioModule",
"UnityEngine.AudioSource,UnityEngine.AudioModule",
"MoreMountains.Feedbacks.MMWiggle,MoreMountains.Feedbacks",
"MoreMountains.Feedbacks.MMFeedbacks,MoreMountains.Feedbacks",
"UnityEngine.UI.ScrollRect,UnityEngine.UI",
"UnityEngine.Rigidbody2D,UnityEngine.Physics2DModule",
"Spine.Unity.SkeletonUtilityBone,spine-unity",
"UnityEngine.UI.Selectable,UnityEngine.UI",
"UnityEngine.EventSystems.EventSystem,UnityEngine.UI",
"UnityEngine.Canvas,UnityEngine.UIModule",
"Cinemachine.CinemachineTargetGroup,Cinemachine",
  };
        }